### ISSUE TITLE
Where is NetSec???

### ISSUE THREAD

**Issue by traversebitree** [BlueJayADAL/JayRadar#30]
Where is NetSec???

**Comment by Klinefelters** [comment]
Sorry I'm not sure I understand what you're asking for. Could you clarify what you're looking for?

**Comment by traversebitree** [comment]
> Sorry I'm not sure I understand what you're asking for. Could you clarify what you're looking for?

Hello, it's from this paper [MalIoT: Scalable and Real-time Malware Traffic Detection for IoT Networks](https://arxiv.org/abs/2304.00623), in Section 5 **Conclusion**.

**Comment by Klinefelters** [comment]
I think you're looking for this repo:
https://github.com/BlueJayADAL/SCARP2020-ML
